pipeline {
  agent any
  tools { 
    nodejs 'node21' // Jenkins > Global Tool Config: NodeJS named "node21"
     allure 'allure'// Jenkins > Global Tool Config: Allure named "allure"
    }
    options {
    timeout(time: 20, unit: 'MINUTES')
  }
  // Binds TEST_CREDS_USR and TEST_CREDS_PSW
  environment { TEST_CREDS = credentials('e2e-test-user') }
  stages {
    stage('Build') {
      steps {
        sh '''
          set -eu
          npm ci
          npx playwright install
        '''
      }
    }
    stage('Test') {
      steps {
        sh '''
          export TEST_USER_NAME="$TEST_CREDS_USR"
          export TEST_PASSWORD="$TEST_CREDS_PSW"
          npm run test:make-apt
        '''
      }
      post {
        always {
         // Publish Allure results generated by the test run
          allure includeProperties: false,
                 jdk: '',
                 results: [[path: 'allure-results']],
                 reportBuildPolicy: 'ALWAYS'
        }
      }
    }
  }
}
