name: Playwright Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main, master]
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        env:
            RUNNER: ${{ secrets.RUNNER }}
            TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
            TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v5
              with:
                  node-version: lts/*
            - name: Install dependencies
              run: npm ci
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run Playwright tests
              run: npm run test:make-apt
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
