name: Playwright Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main, master]
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        env:
            RUNNER: ${{ secrets.RUNNER }}
            TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
            TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v5
              with:
                  node-version: lts/*
            - name: Install dependencies
              run: npm ci
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Install Allure commandline
              run: npm install -g allure-commandline --save-dev
            - name: Run Playwright tests
              run: npm run test:make-apt
            - name: Generate Allure Report
              run: |
                allure generate allure-results --clean -o allure-report
                allure open -h 127.0.0.1 -p 5050 allure-report &
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: allure-report
                  path: allure-report/
                  retention-days: 30
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: allure-results
                  path: allure-results/
                  retention-days: 30
